// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dot_product_dot_product,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.207000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4234,HLS_SYN_LUT=2150,HLS_VERSION=2025_1}" *)

module dot_product (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_0,
        x_1,
        x_2,
        x_3,
        x_4,
        x_5,
        x_6,
        x_7,
        x_8,
        x_9,
        x_10,
        x_11,
        x_12,
        x_13,
        x_14,
        x_15,
        x_16,
        x_17,
        x_18,
        x_19,
        x_20,
        x_21,
        x_22,
        x_23,
        x_24,
        x_25,
        x_26,
        x_27,
        x_28,
        x_29,
        x_30,
        x_31,
        z_0,
        z_1,
        z_2,
        z_3,
        z_4,
        z_5,
        z_6,
        z_7,
        z_8,
        z_9,
        z_10,
        z_11,
        z_12,
        z_13,
        z_14,
        z_15,
        z_16,
        z_17,
        z_18,
        z_19,
        z_20,
        z_21,
        z_22,
        z_23,
        z_24,
        z_25,
        z_26,
        z_27,
        z_28,
        z_29,
        z_30,
        z_31,
        ap_return
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] x_0;
input  [31:0] x_1;
input  [31:0] x_2;
input  [31:0] x_3;
input  [31:0] x_4;
input  [31:0] x_5;
input  [31:0] x_6;
input  [31:0] x_7;
input  [31:0] x_8;
input  [31:0] x_9;
input  [31:0] x_10;
input  [31:0] x_11;
input  [31:0] x_12;
input  [31:0] x_13;
input  [31:0] x_14;
input  [31:0] x_15;
input  [31:0] x_16;
input  [31:0] x_17;
input  [31:0] x_18;
input  [31:0] x_19;
input  [31:0] x_20;
input  [31:0] x_21;
input  [31:0] x_22;
input  [31:0] x_23;
input  [31:0] x_24;
input  [31:0] x_25;
input  [31:0] x_26;
input  [31:0] x_27;
input  [31:0] x_28;
input  [31:0] x_29;
input  [31:0] x_30;
input  [31:0] x_31;
input  [31:0] z_0;
input  [31:0] z_1;
input  [31:0] z_2;
input  [31:0] z_3;
input  [31:0] z_4;
input  [31:0] z_5;
input  [31:0] z_6;
input  [31:0] z_7;
input  [31:0] z_8;
input  [31:0] z_9;
input  [31:0] z_10;
input  [31:0] z_11;
input  [31:0] z_12;
input  [31:0] z_13;
input  [31:0] z_14;
input  [31:0] z_15;
input  [31:0] z_16;
input  [31:0] z_17;
input  [31:0] z_18;
input  [31:0] z_19;
input  [31:0] z_20;
input  [31:0] z_21;
input  [31:0] z_22;
input  [31:0] z_23;
input  [31:0] z_24;
input  [31:0] z_25;
input  [31:0] z_26;
input  [31:0] z_27;
input  [31:0] z_28;
input  [31:0] z_29;
input  [31:0] z_30;
input  [31:0] z_31;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_fu_530_p2;
reg   [31:0] reg_674;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [31:0] grp_fu_536_p2;
reg   [31:0] reg_678;
wire   [31:0] grp_fu_542_p2;
reg   [31:0] reg_682;
wire   [31:0] grp_fu_548_p2;
reg   [31:0] reg_686;
wire   [31:0] grp_fu_562_p2;
reg   [31:0] reg_690;
wire   [31:0] grp_fu_568_p2;
reg   [31:0] reg_694;
wire   [31:0] grp_fu_574_p2;
reg   [31:0] reg_698;
wire   [31:0] grp_fu_580_p2;
reg   [31:0] reg_702;
wire   [31:0] grp_fu_586_p2;
reg   [31:0] mul_ln12_12_reg_1161;
wire   [31:0] grp_fu_592_p2;
reg   [31:0] mul_ln12_13_reg_1166;
wire   [31:0] grp_fu_598_p2;
reg   [31:0] mul_ln12_14_reg_1171;
wire   [31:0] grp_fu_604_p2;
reg   [31:0] mul_ln12_15_reg_1176;
wire   [31:0] grp_fu_610_p2;
reg   [31:0] mul_ln12_16_reg_1181;
wire   [31:0] grp_fu_616_p2;
reg   [31:0] mul_ln12_17_reg_1186;
wire   [31:0] grp_fu_622_p2;
reg   [31:0] mul_ln12_18_reg_1191;
wire   [31:0] grp_fu_628_p2;
reg   [31:0] mul_ln12_19_reg_1196;
wire   [31:0] grp_fu_634_p2;
reg   [31:0] mul_ln12_24_reg_1201;
wire   [31:0] grp_fu_640_p2;
reg   [31:0] mul_ln12_25_reg_1206;
wire   [31:0] grp_fu_646_p2;
reg   [31:0] mul_ln12_26_reg_1211;
wire   [31:0] grp_fu_652_p2;
reg   [31:0] mul_ln12_27_reg_1216;
wire   [31:0] add_ln12_27_fu_736_p2;
reg   [31:0] add_ln12_27_reg_1221;
wire   [31:0] add_ln12_5_fu_750_p2;
reg   [31:0] add_ln12_5_reg_1226;
wire   [31:0] add_ln12_12_fu_764_p2;
reg   [31:0] add_ln12_12_reg_1231;
wire   [31:0] add_ln12_17_fu_778_p2;
reg   [31:0] add_ln12_17_reg_1236;
wire   [31:0] add_ln12_20_fu_790_p2;
reg   [31:0] add_ln12_20_reg_1241;
wire   [31:0] add_ln12_28_fu_796_p2;
reg   [31:0] add_ln12_28_reg_1246;
wire   [31:0] add_ln12_6_fu_813_p2;
reg   [31:0] add_ln12_6_reg_1251;
wire    ap_CS_fsm_state5;
wire   [31:0] add_ln12_13_fu_818_p2;
reg   [31:0] add_ln12_13_reg_1256;
wire   [31:0] add_ln12_29_fu_827_p2;
reg   [31:0] add_ln12_29_reg_1261;
reg  signed [31:0] grp_fu_530_p0;
reg  signed [31:0] grp_fu_530_p1;
reg  signed [31:0] grp_fu_536_p0;
reg  signed [31:0] grp_fu_536_p1;
reg  signed [31:0] grp_fu_542_p0;
reg  signed [31:0] grp_fu_542_p1;
reg  signed [31:0] grp_fu_548_p0;
reg  signed [31:0] grp_fu_548_p1;
reg  signed [31:0] grp_fu_562_p0;
reg  signed [31:0] grp_fu_562_p1;
reg  signed [31:0] grp_fu_568_p0;
reg  signed [31:0] grp_fu_568_p1;
reg  signed [31:0] grp_fu_574_p0;
reg  signed [31:0] grp_fu_574_p1;
reg  signed [31:0] grp_fu_580_p0;
reg  signed [31:0] grp_fu_580_p1;
wire   [31:0] grp_fu_706_p2;
wire   [31:0] grp_fu_718_p2;
wire   [31:0] add_ln12_25_fu_730_p2;
wire   [31:0] add_ln12_4_fu_746_p2;
wire   [31:0] add_ln12_3_fu_742_p2;
wire   [31:0] add_ln12_11_fu_760_p2;
wire   [31:0] add_ln12_10_fu_756_p2;
wire   [31:0] add_ln12_16_fu_774_p2;
wire   [31:0] add_ln12_15_fu_770_p2;
wire   [31:0] grp_fu_712_p2;
wire   [31:0] add_ln12_18_fu_784_p2;
wire   [31:0] grp_fu_724_p2;
wire   [31:0] add_ln12_fu_801_p2;
wire   [31:0] add_ln12_2_fu_807_p2;
wire   [31:0] add_ln12_21_fu_823_p2;
wire    ap_CS_fsm_state6;
wire   [31:0] add_ln12_14_fu_832_p2;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_530_p0),
    .din1(grp_fu_530_p1),
    .ce(1'b1),
    .dout(grp_fu_530_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_536_p0),
    .din1(grp_fu_536_p1),
    .ce(1'b1),
    .dout(grp_fu_536_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_542_p0),
    .din1(grp_fu_542_p1),
    .ce(1'b1),
    .dout(grp_fu_542_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_548_p0),
    .din1(grp_fu_548_p1),
    .ce(1'b1),
    .dout(grp_fu_548_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_562_p0),
    .din1(grp_fu_562_p1),
    .ce(1'b1),
    .dout(grp_fu_562_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_568_p0),
    .din1(grp_fu_568_p1),
    .ce(1'b1),
    .dout(grp_fu_568_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_574_p0),
    .din1(grp_fu_574_p1),
    .ce(1'b1),
    .dout(grp_fu_574_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_580_p0),
    .din1(grp_fu_580_p1),
    .ce(1'b1),
    .dout(grp_fu_580_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_19),
    .din1(x_19),
    .ce(1'b1),
    .dout(grp_fu_586_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_18),
    .din1(x_18),
    .ce(1'b1),
    .dout(grp_fu_592_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_17),
    .din1(x_17),
    .ce(1'b1),
    .dout(grp_fu_598_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_16),
    .din1(x_16),
    .ce(1'b1),
    .dout(grp_fu_604_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_15),
    .din1(x_15),
    .ce(1'b1),
    .dout(grp_fu_610_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_14),
    .din1(x_14),
    .ce(1'b1),
    .dout(grp_fu_616_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_13),
    .din1(x_13),
    .ce(1'b1),
    .dout(grp_fu_622_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_12),
    .din1(x_12),
    .ce(1'b1),
    .dout(grp_fu_628_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_7),
    .din1(x_7),
    .ce(1'b1),
    .dout(grp_fu_634_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_6),
    .din1(x_6),
    .ce(1'b1),
    .dout(grp_fu_640_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_5),
    .din1(x_5),
    .ce(1'b1),
    .dout(grp_fu_646_p2)
);

dot_product_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z_4),
    .din1(x_4),
    .ce(1'b1),
    .dout(grp_fu_652_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln12_12_reg_1231 <= add_ln12_12_fu_764_p2;
        add_ln12_17_reg_1236 <= add_ln12_17_fu_778_p2;
        add_ln12_20_reg_1241 <= add_ln12_20_fu_790_p2;
        add_ln12_28_reg_1246 <= add_ln12_28_fu_796_p2;
        add_ln12_5_reg_1226 <= add_ln12_5_fu_750_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln12_13_reg_1256 <= add_ln12_13_fu_818_p2;
        add_ln12_29_reg_1261 <= add_ln12_29_fu_827_p2;
        add_ln12_6_reg_1251 <= add_ln12_6_fu_813_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln12_27_reg_1221 <= add_ln12_27_fu_736_p2;
        mul_ln12_12_reg_1161 <= grp_fu_586_p2;
        mul_ln12_13_reg_1166 <= grp_fu_592_p2;
        mul_ln12_14_reg_1171 <= grp_fu_598_p2;
        mul_ln12_15_reg_1176 <= grp_fu_604_p2;
        mul_ln12_16_reg_1181 <= grp_fu_610_p2;
        mul_ln12_17_reg_1186 <= grp_fu_616_p2;
        mul_ln12_18_reg_1191 <= grp_fu_622_p2;
        mul_ln12_19_reg_1196 <= grp_fu_628_p2;
        mul_ln12_24_reg_1201 <= grp_fu_634_p2;
        mul_ln12_25_reg_1206 <= grp_fu_640_p2;
        mul_ln12_26_reg_1211 <= grp_fu_646_p2;
        mul_ln12_27_reg_1216 <= grp_fu_652_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_674 <= grp_fu_530_p2;
        reg_678 <= grp_fu_536_p2;
        reg_682 <= grp_fu_542_p2;
        reg_686 <= grp_fu_548_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_690 <= grp_fu_562_p2;
        reg_694 <= grp_fu_568_p2;
        reg_698 <= grp_fu_574_p2;
        reg_702 <= grp_fu_580_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_530_p0 = z_11;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_530_p0 = z_27;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_530_p0 = z_31;
    end else begin
        grp_fu_530_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_530_p1 = x_11;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_530_p1 = x_27;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_530_p1 = x_31;
    end else begin
        grp_fu_530_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_536_p0 = z_10;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_536_p0 = z_26;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_536_p0 = z_30;
    end else begin
        grp_fu_536_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_536_p1 = x_10;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_536_p1 = x_26;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_536_p1 = x_30;
    end else begin
        grp_fu_536_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_542_p0 = z_9;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_542_p0 = z_25;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_542_p0 = z_29;
    end else begin
        grp_fu_542_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_542_p1 = x_9;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_542_p1 = x_25;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_542_p1 = x_29;
    end else begin
        grp_fu_542_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_548_p0 = z_8;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_548_p0 = z_24;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_548_p0 = z_28;
    end else begin
        grp_fu_548_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_548_p1 = x_8;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_548_p1 = x_24;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_548_p1 = x_28;
    end else begin
        grp_fu_548_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_562_p0 = z_3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_562_p0 = z_23;
    end else begin
        grp_fu_562_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_562_p1 = x_3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_562_p1 = x_23;
    end else begin
        grp_fu_562_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_568_p0 = z_2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_568_p0 = z_22;
    end else begin
        grp_fu_568_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_568_p1 = x_2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_568_p1 = x_22;
    end else begin
        grp_fu_568_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_574_p0 = z_0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_574_p0 = z_21;
    end else begin
        grp_fu_574_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_574_p1 = x_0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_574_p1 = x_21;
    end else begin
        grp_fu_574_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_580_p0 = z_1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_580_p0 = z_20;
    end else begin
        grp_fu_580_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_580_p1 = x_1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_580_p1 = x_20;
    end else begin
        grp_fu_580_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12_10_fu_756_p2 = (mul_ln12_19_reg_1196 + mul_ln12_18_reg_1191);

assign add_ln12_11_fu_760_p2 = (mul_ln12_17_reg_1186 + mul_ln12_16_reg_1181);

assign add_ln12_12_fu_764_p2 = (add_ln12_11_fu_760_p2 + add_ln12_10_fu_756_p2);

assign add_ln12_13_fu_818_p2 = (add_ln12_12_reg_1231 + grp_fu_724_p2);

assign add_ln12_14_fu_832_p2 = (add_ln12_13_reg_1256 + add_ln12_6_reg_1251);

assign add_ln12_15_fu_770_p2 = (mul_ln12_15_reg_1176 + mul_ln12_14_reg_1171);

assign add_ln12_16_fu_774_p2 = (mul_ln12_13_reg_1166 + mul_ln12_12_reg_1161);

assign add_ln12_17_fu_778_p2 = (add_ln12_16_fu_774_p2 + add_ln12_15_fu_770_p2);

assign add_ln12_18_fu_784_p2 = (reg_702 + reg_698);

assign add_ln12_20_fu_790_p2 = (grp_fu_712_p2 + add_ln12_18_fu_784_p2);

assign add_ln12_21_fu_823_p2 = (add_ln12_20_reg_1241 + add_ln12_17_reg_1236);

assign add_ln12_25_fu_730_p2 = (reg_686 + reg_682);

assign add_ln12_27_fu_736_p2 = (grp_fu_706_p2 + add_ln12_25_fu_730_p2);

assign add_ln12_28_fu_796_p2 = (add_ln12_27_reg_1221 + grp_fu_724_p2);

assign add_ln12_29_fu_827_p2 = (add_ln12_28_reg_1246 + add_ln12_21_fu_823_p2);

assign add_ln12_2_fu_807_p2 = (grp_fu_712_p2 + add_ln12_fu_801_p2);

assign add_ln12_3_fu_742_p2 = (mul_ln12_27_reg_1216 + mul_ln12_26_reg_1211);

assign add_ln12_4_fu_746_p2 = (mul_ln12_25_reg_1206 + mul_ln12_24_reg_1201);

assign add_ln12_5_fu_750_p2 = (add_ln12_4_fu_746_p2 + add_ln12_3_fu_742_p2);

assign add_ln12_6_fu_813_p2 = (add_ln12_5_reg_1226 + add_ln12_2_fu_807_p2);

assign add_ln12_fu_801_p2 = (reg_702 + reg_698);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_return = (add_ln12_29_reg_1261 + add_ln12_14_fu_832_p2);

assign grp_fu_706_p2 = (reg_678 + reg_674);

assign grp_fu_712_p2 = (reg_694 + reg_690);

assign grp_fu_718_p2 = (reg_686 + reg_682);

assign grp_fu_724_p2 = (grp_fu_706_p2 + grp_fu_718_p2);

endmodule //dot_product
