-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dot_product is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_16 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_17 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_18 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_19 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_20 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_21 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_22 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_23 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_24 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_25 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_26 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_27 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_28 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_29 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_30 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_31 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_16 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_17 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_18 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_19 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_20 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_21 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_22 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_23 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_24 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_25 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_26 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_27 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_28 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_29 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_30 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_31 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of dot_product is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dot_product_dot_product,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.207000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4234,HLS_SYN_LUT=2150,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_530_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_674 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_536_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_678 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_542_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_682 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_548_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_686 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_562_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_690 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_568_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_694 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_574_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_698 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_580_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_702 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_586_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_12_reg_1161 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_592_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_13_reg_1166 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_598_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_14_reg_1171 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_604_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_15_reg_1176 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_610_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_16_reg_1181 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_616_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_17_reg_1186 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_622_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_18_reg_1191 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_628_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_19_reg_1196 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_634_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_24_reg_1201 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_640_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_25_reg_1206 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_646_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_26_reg_1211 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_652_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_27_reg_1216 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_27_fu_736_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_27_reg_1221 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_5_fu_750_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_5_reg_1226 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_12_fu_764_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_12_reg_1231 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_17_fu_778_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_17_reg_1236 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_20_fu_790_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_20_reg_1241 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_28_fu_796_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_28_reg_1246 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_6_fu_813_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_6_reg_1251 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln12_13_fu_818_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_13_reg_1256 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_29_fu_827_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_29_reg_1261 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_530_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_530_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_536_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_536_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_542_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_542_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_548_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_548_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_562_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_562_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_568_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_568_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_574_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_574_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_580_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_580_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_706_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_718_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_25_fu_730_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_4_fu_746_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_3_fu_742_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_11_fu_760_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_10_fu_756_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_16_fu_774_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_15_fu_770_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_712_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_18_fu_784_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_724_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_fu_801_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_2_fu_807_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_21_fu_823_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal add_ln12_14_fu_832_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dot_product_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mul_32s_32s_32_2_1_U1 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_530_p0,
        din1 => grp_fu_530_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_530_p2);

    mul_32s_32s_32_2_1_U2 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_536_p0,
        din1 => grp_fu_536_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_536_p2);

    mul_32s_32s_32_2_1_U3 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_542_p0,
        din1 => grp_fu_542_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_542_p2);

    mul_32s_32s_32_2_1_U4 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_548_p0,
        din1 => grp_fu_548_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_548_p2);

    mul_32s_32s_32_2_1_U5 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_562_p0,
        din1 => grp_fu_562_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_562_p2);

    mul_32s_32s_32_2_1_U6 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_568_p0,
        din1 => grp_fu_568_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_568_p2);

    mul_32s_32s_32_2_1_U7 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_574_p0,
        din1 => grp_fu_574_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_574_p2);

    mul_32s_32s_32_2_1_U8 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_580_p0,
        din1 => grp_fu_580_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_580_p2);

    mul_32s_32s_32_2_1_U9 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_19,
        din1 => x_19,
        ce => ap_const_logic_1,
        dout => grp_fu_586_p2);

    mul_32s_32s_32_2_1_U10 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_18,
        din1 => x_18,
        ce => ap_const_logic_1,
        dout => grp_fu_592_p2);

    mul_32s_32s_32_2_1_U11 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_17,
        din1 => x_17,
        ce => ap_const_logic_1,
        dout => grp_fu_598_p2);

    mul_32s_32s_32_2_1_U12 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_16,
        din1 => x_16,
        ce => ap_const_logic_1,
        dout => grp_fu_604_p2);

    mul_32s_32s_32_2_1_U13 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_15,
        din1 => x_15,
        ce => ap_const_logic_1,
        dout => grp_fu_610_p2);

    mul_32s_32s_32_2_1_U14 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_14,
        din1 => x_14,
        ce => ap_const_logic_1,
        dout => grp_fu_616_p2);

    mul_32s_32s_32_2_1_U15 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_13,
        din1 => x_13,
        ce => ap_const_logic_1,
        dout => grp_fu_622_p2);

    mul_32s_32s_32_2_1_U16 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_12,
        din1 => x_12,
        ce => ap_const_logic_1,
        dout => grp_fu_628_p2);

    mul_32s_32s_32_2_1_U17 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_7,
        din1 => x_7,
        ce => ap_const_logic_1,
        dout => grp_fu_634_p2);

    mul_32s_32s_32_2_1_U18 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_6,
        din1 => x_6,
        ce => ap_const_logic_1,
        dout => grp_fu_640_p2);

    mul_32s_32s_32_2_1_U19 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_5,
        din1 => x_5,
        ce => ap_const_logic_1,
        dout => grp_fu_646_p2);

    mul_32s_32s_32_2_1_U20 : component dot_product_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => z_4,
        din1 => x_4,
        ce => ap_const_logic_1,
        dout => grp_fu_652_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln12_12_reg_1231 <= add_ln12_12_fu_764_p2;
                add_ln12_17_reg_1236 <= add_ln12_17_fu_778_p2;
                add_ln12_20_reg_1241 <= add_ln12_20_fu_790_p2;
                add_ln12_28_reg_1246 <= add_ln12_28_fu_796_p2;
                add_ln12_5_reg_1226 <= add_ln12_5_fu_750_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln12_13_reg_1256 <= add_ln12_13_fu_818_p2;
                add_ln12_29_reg_1261 <= add_ln12_29_fu_827_p2;
                add_ln12_6_reg_1251 <= add_ln12_6_fu_813_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln12_27_reg_1221 <= add_ln12_27_fu_736_p2;
                mul_ln12_12_reg_1161 <= grp_fu_586_p2;
                mul_ln12_13_reg_1166 <= grp_fu_592_p2;
                mul_ln12_14_reg_1171 <= grp_fu_598_p2;
                mul_ln12_15_reg_1176 <= grp_fu_604_p2;
                mul_ln12_16_reg_1181 <= grp_fu_610_p2;
                mul_ln12_17_reg_1186 <= grp_fu_616_p2;
                mul_ln12_18_reg_1191 <= grp_fu_622_p2;
                mul_ln12_19_reg_1196 <= grp_fu_628_p2;
                mul_ln12_24_reg_1201 <= grp_fu_634_p2;
                mul_ln12_25_reg_1206 <= grp_fu_640_p2;
                mul_ln12_26_reg_1211 <= grp_fu_646_p2;
                mul_ln12_27_reg_1216 <= grp_fu_652_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then
                reg_674 <= grp_fu_530_p2;
                reg_678 <= grp_fu_536_p2;
                reg_682 <= grp_fu_542_p2;
                reg_686 <= grp_fu_548_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then
                reg_690 <= grp_fu_562_p2;
                reg_694 <= grp_fu_568_p2;
                reg_698 <= grp_fu_574_p2;
                reg_702 <= grp_fu_580_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln12_10_fu_756_p2 <= std_logic_vector(unsigned(mul_ln12_19_reg_1196) + unsigned(mul_ln12_18_reg_1191));
    add_ln12_11_fu_760_p2 <= std_logic_vector(unsigned(mul_ln12_17_reg_1186) + unsigned(mul_ln12_16_reg_1181));
    add_ln12_12_fu_764_p2 <= std_logic_vector(unsigned(add_ln12_11_fu_760_p2) + unsigned(add_ln12_10_fu_756_p2));
    add_ln12_13_fu_818_p2 <= std_logic_vector(unsigned(add_ln12_12_reg_1231) + unsigned(grp_fu_724_p2));
    add_ln12_14_fu_832_p2 <= std_logic_vector(unsigned(add_ln12_13_reg_1256) + unsigned(add_ln12_6_reg_1251));
    add_ln12_15_fu_770_p2 <= std_logic_vector(unsigned(mul_ln12_15_reg_1176) + unsigned(mul_ln12_14_reg_1171));
    add_ln12_16_fu_774_p2 <= std_logic_vector(unsigned(mul_ln12_13_reg_1166) + unsigned(mul_ln12_12_reg_1161));
    add_ln12_17_fu_778_p2 <= std_logic_vector(unsigned(add_ln12_16_fu_774_p2) + unsigned(add_ln12_15_fu_770_p2));
    add_ln12_18_fu_784_p2 <= std_logic_vector(unsigned(reg_702) + unsigned(reg_698));
    add_ln12_20_fu_790_p2 <= std_logic_vector(unsigned(grp_fu_712_p2) + unsigned(add_ln12_18_fu_784_p2));
    add_ln12_21_fu_823_p2 <= std_logic_vector(unsigned(add_ln12_20_reg_1241) + unsigned(add_ln12_17_reg_1236));
    add_ln12_25_fu_730_p2 <= std_logic_vector(unsigned(reg_686) + unsigned(reg_682));
    add_ln12_27_fu_736_p2 <= std_logic_vector(unsigned(grp_fu_706_p2) + unsigned(add_ln12_25_fu_730_p2));
    add_ln12_28_fu_796_p2 <= std_logic_vector(unsigned(add_ln12_27_reg_1221) + unsigned(grp_fu_724_p2));
    add_ln12_29_fu_827_p2 <= std_logic_vector(unsigned(add_ln12_28_reg_1246) + unsigned(add_ln12_21_fu_823_p2));
    add_ln12_2_fu_807_p2 <= std_logic_vector(unsigned(grp_fu_712_p2) + unsigned(add_ln12_fu_801_p2));
    add_ln12_3_fu_742_p2 <= std_logic_vector(unsigned(mul_ln12_27_reg_1216) + unsigned(mul_ln12_26_reg_1211));
    add_ln12_4_fu_746_p2 <= std_logic_vector(unsigned(mul_ln12_25_reg_1206) + unsigned(mul_ln12_24_reg_1201));
    add_ln12_5_fu_750_p2 <= std_logic_vector(unsigned(add_ln12_4_fu_746_p2) + unsigned(add_ln12_3_fu_742_p2));
    add_ln12_6_fu_813_p2 <= std_logic_vector(unsigned(add_ln12_5_reg_1226) + unsigned(add_ln12_2_fu_807_p2));
    add_ln12_fu_801_p2 <= std_logic_vector(unsigned(reg_702) + unsigned(reg_698));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= std_logic_vector(unsigned(add_ln12_29_reg_1261) + unsigned(add_ln12_14_fu_832_p2));

    grp_fu_530_p0_assign_proc : process(ap_CS_fsm_state1, z_11, z_27, z_31, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_530_p0 <= z_11;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_530_p0 <= z_27;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_530_p0 <= z_31;
        else 
            grp_fu_530_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_530_p1_assign_proc : process(ap_CS_fsm_state1, x_11, x_27, x_31, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_530_p1 <= x_11;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_530_p1 <= x_27;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_530_p1 <= x_31;
        else 
            grp_fu_530_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_536_p0_assign_proc : process(ap_CS_fsm_state1, z_10, z_26, z_30, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_536_p0 <= z_10;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_536_p0 <= z_26;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_536_p0 <= z_30;
        else 
            grp_fu_536_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_536_p1_assign_proc : process(ap_CS_fsm_state1, x_10, x_26, x_30, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_536_p1 <= x_10;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_536_p1 <= x_26;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_536_p1 <= x_30;
        else 
            grp_fu_536_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_542_p0_assign_proc : process(ap_CS_fsm_state1, z_9, z_25, z_29, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_542_p0 <= z_9;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_542_p0 <= z_25;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_542_p0 <= z_29;
        else 
            grp_fu_542_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_542_p1_assign_proc : process(ap_CS_fsm_state1, x_9, x_25, x_29, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_542_p1 <= x_9;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_542_p1 <= x_25;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_542_p1 <= x_29;
        else 
            grp_fu_542_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_548_p0_assign_proc : process(ap_CS_fsm_state1, z_8, z_24, z_28, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_548_p0 <= z_8;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_548_p0 <= z_24;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_548_p0 <= z_28;
        else 
            grp_fu_548_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_548_p1_assign_proc : process(ap_CS_fsm_state1, x_8, x_24, x_28, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_548_p1 <= x_8;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_548_p1 <= x_24;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_548_p1 <= x_28;
        else 
            grp_fu_548_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_562_p0_assign_proc : process(z_3, z_23, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_562_p0 <= z_3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_562_p0 <= z_23;
        else 
            grp_fu_562_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_562_p1_assign_proc : process(x_3, x_23, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_562_p1 <= x_3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_562_p1 <= x_23;
        else 
            grp_fu_562_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_568_p0_assign_proc : process(z_2, z_22, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_568_p0 <= z_2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_568_p0 <= z_22;
        else 
            grp_fu_568_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_568_p1_assign_proc : process(x_2, x_22, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_568_p1 <= x_2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_568_p1 <= x_22;
        else 
            grp_fu_568_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_574_p0_assign_proc : process(z_0, z_21, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_574_p0 <= z_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_574_p0 <= z_21;
        else 
            grp_fu_574_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_574_p1_assign_proc : process(x_0, x_21, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_574_p1 <= x_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_574_p1 <= x_21;
        else 
            grp_fu_574_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_580_p0_assign_proc : process(z_1, z_20, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_580_p0 <= z_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_580_p0 <= z_20;
        else 
            grp_fu_580_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_580_p1_assign_proc : process(x_1, x_20, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_580_p1 <= x_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_580_p1 <= x_20;
        else 
            grp_fu_580_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_706_p2 <= std_logic_vector(unsigned(reg_678) + unsigned(reg_674));
    grp_fu_712_p2 <= std_logic_vector(unsigned(reg_694) + unsigned(reg_690));
    grp_fu_718_p2 <= std_logic_vector(unsigned(reg_686) + unsigned(reg_682));
    grp_fu_724_p2 <= std_logic_vector(unsigned(grp_fu_706_p2) + unsigned(grp_fu_718_p2));
end behav;
