

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
		"CDFG" : "dot_product",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "x_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_18", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_21", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_23", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_24", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_25", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_26", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_27", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_29", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_30", "Type" : "None", "Direction" : "I"},
			{"Name" : "x_31", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_18", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_21", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_23", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_24", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_25", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_26", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_27", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_29", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_30", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_31", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U1", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U2", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U3", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U4", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U5", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U6", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U7", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U8", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U9", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U10", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U11", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U12", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U13", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U14", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U15", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U16", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U17", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U18", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U19", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U20", "Parent" : "0"}]}
